id = "compline"
name = "Compline"
description = "A color palette for Deep contemplation and work"
version = "0.1.0"
schema_version = 1
authors = ["Joshua Blais"]
repository = "https://github.com/jblais493/compline.git"
